# Generated by Django 4.1 on 2022-09-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=30, verbose_name='Domain Name')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_id', models.CharField(max_length=5, verbose_name='Question Id')),
                ('que_title', models.CharField(max_length=150, verbose_name='Title Name')),
                ('que_link', models.URLField(verbose_name='Question Link')),
                ('que_difficulty', models.CharField(max_length=10, verbose_name='Difficulty Level')),
                ('dsa_sheet', models.CharField(max_length=2, verbose_name='DSA Sheet')),
                ('que_domain', models.ManyToManyField(blank=True, to='Dashboard.domain')),
            ],
        ),
    ]
